name: dartclassgenerator
description: A Flutter that can generate Dart classes. Runs on Android and Web.
publish_to: 'none'
version: 0.0.9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  groovin_widgets: ^1.5.0+1
  google_fonts: ^0.5.0+1
  dart_style: ^1.3.4
  material_design_icons_flutter: ^4.0.5145
  provider: ^4.0.5
  rxdart: ^0.24.0
  url_launcher: ^5.4.2
  url_launcher_web: ^0.1.1+1
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
  flutter_syntax_view:
    git: https://github.com/rodydavis/flutter_syntax_view
    #path: ../../flutter_syntax_view
  syntax_highlighter:
    git: https://github.com/rodydavis/syntax_highlighter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
